### ISSUE TITLE
get_bgp_neighbor does not support inet flow address families

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-junos#27]
### Description of Issue/Question

Fails when trying to retrieve the BGP neighbors using `get_bgp_neighbors`.
### napalm-junos version

```
napalm-junos==0.2.1
```
### JunOS version

```
Junos: 13.3R6.5
```
### Steps to Reproduce the Issue
- Configure BGP to use inet flow: `set protocols bgp family inet flow`
- Open the connection with the device
- call `get_bgp_neighbors`
### Error Traceback

```
>>> j.get_bgp_neighbors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/napalm-junos/napalm_junos/junos.py", line 374, in get_bgp_neighbors
    peer['address_family'] = self._parse_route_stats(neighbor_data)
  File "/state/home/mircea/napalm-junos/napalm_junos/junos.py", line 333, in _parse_route_stats
    family = self._get_address_family(table)
  File "/state/home/mircea/napalm-junos/napalm_junos/junos.py", line 325, in _get_address_family
    return address_family_mapping[family]
KeyError: 'inetflow'
```

**Comment by kderynski** [comment]
@mirceaulinic I have managed to reproduce this issue also on Junos: `12.1X47-D15.4`. Fix seems to be very easy. `inetflow` added to `address_family_mapping` fixed this particular issue  ex.

```
   address_family_mapping = {
        'inet': 'ipv4',
        'inet6': 'ipv6',
        'inetflow': 'flow'
    }
```

I am checking if there is more exceptions like this for example with different NLRIs.

**Comment by mirceaulinic** [comment]
Thanks @kderynski for looking into this. Will assign this to you.

**Comment by kderynski** [comment]
Cool, probably the same situation is in #39 I'll check it.

**Comment by kderynski** [comment]
I have checked it and issue will be present for any table/NLRI different from `inet` and `inet6`, so for example `l2vpn`,  `l3vpn`, `evpn` and other types. I think it would be better to return table name if there is no key for this name in `address_family_mapping`. Second option is to add all types in `address_family_mapping` dict as we want to keep unified names across different platforms.

**Comment by mirceaulinic** [comment]
@kderynski please go ahead and let us know when you have anything to review :)

**Comment by mirceaulinic** [comment]
Fixed via https://github.com/napalm-automation/napalm-junos/pull/47
