### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-junos#56]
See details in the parent issue napalm-automation/napalm#199

**Comment by ktbyers** [comment]
Python3 issue in PYEZ with parsing YAML: https://github.com/Juniper/py-junos-eznc/issues/639

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-junos/commit/c40cc819d8de6695468869ac45a64a18045930ce
